class ErrorCodes:
    SUCCESS = 1
    UPDATE = 2
    END_CONNECTION = 3
    INVALID_SERVER_TYPE = 4
    INVALID_KEY_SESSION = 0x100
    INVALID_SESSION_MATCH = 0x110
    ALREADY_AUTHORIZED = 0x120
    SERVER_LIMIT_REACHED = 0x130
    SERVER_NAME_USED = 0x140
